language: ruby
rvm:
  - 2.6.4
script:
  - bundle exec haml-lint
  - bundle exec rubocop
  - bundle exec rspec
  - yarn install --ignore-engines
  - bundle exec rails assets:precompile
  - yarn run eslint
  - yarn run stylelint
