email: me@jonhue.me
social:
  twitter: https://twitter.com/_jonhue
  github: https://github.com/jonhue
  medium: https://medium.com/@jonhue
  linkedin: https://linkedin.com/in/jonhue
  behance: https://behance.net/jonhue
badge:
  android: https://play.google.com/intl/en_us/badges/images/generic/en_badge_web_generic.png
  ios: https://devimages-cdn.apple.com/app-store/marketing/guidelines/images/exhibit-1-1-preferred_2x.png
  windows: https://assets.windowsphone.com/85864462-9c82-451e-9355-a3d5f874397a/English_get-it-from-MS_InvariantCulture_Default.png

github:
  repos: https://api.github.com/users/jonhue/repos
