email: me@jonhue.me
social:
  twitter: https://twitter.com/_jonhue
  github: https://github.com/jonhue
  medium: https://medium.com/@jonhue
  linkedin: https://linkedin.com/in/jonhue
  behance: https://behance.net/jonhue

github:
  repos: https://api.github.com/users/jonhue/repos
