default: &default
    concurrency: <%= Settings.sidekiq.concurrency %>


production:
    <<: *default
    timeout: <%= Settings.sidekiq.timeout %>

development:
    <<: *default

test:
    <<: *default
